# Generated by Django 4.1.1 on 2022-10-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_contente_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='thor.png', upload_to=''),
        ),
    ]
